# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

jobs:
- job: build_app
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

- job: notify_splunk
  pool: server

  steps:
  - task: Splunk Observability Cloud Events@0
    inputs:
      splunk-events-api: 'Splunk APAC SE org'
      environment: 'test'
      eventType: 'ZR Azure Build Deployment'